### ISSUE TITLE
why don't you give correct info

### ISSUE THREAD

**Issue by MonicaJae** [msquared2/columns_ui#5]
what's the deal with you zipping this with a .zip program?  this is f-up you should also give the correct information regarding installing a component.  inserting a dll into the component directory is incorrect and doesn't work and i think you know that.  what the hell. foobar doesn't read component dlls

**Comment by zao** [comment]
Hi and welcome to the Internet, please try to be civil.

Some components were primarily developed in the era before user-components and as such, their delivery method and instructions predate that directory and `.fb2k-component` files.

Note that foobar2000 still accepts naked `.dll` files if you drag them onto the Components list in Preferences, and that foobar2000 has at some point in time automatically migrated recognized third party components from the `components` directory to a subdirectory of `user-components`, explicitly to allow for legacy instructions to continue to work.

There does not seem to be any instructions in this repository that encourages legacy behavior. Is your feedback for the `you.be` website hosting the releases? I'm sure the author would be happy to implement feedback if presented in a constructive manner.

**Comment by msquared2** [comment]
No, I'm not really fully up-to-date with how to distribute foobar2000 components. As @zao mentioned, the instructions were written some time ago and were correct when written.

I will inform myself and update the instructions and archive when I have a bit of time. Thanks.
